name: Test

on:
  # push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Build fonts
        run: make all

      - name: Check output
        run: test -n "$(find fonts -path '*/dist/*.ttf' -type f -print -quit)"
